# Generated by Django 3.2.19 on 2023-06-29 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20230628_1512'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='head_clas',
            field=models.CharField(choices=[('Немає', 'Немає'), ('1-A', '1-A'), ('1-B', '1-B'), ('2-A', '2-A'), ('2-B', '2-B'), ('3-A', '3-A'), ('3-B', '3-B'), ('4-A', '4-A'), ('4-B', '4-B'), ('5-A', '5-A'), ('5-B', '5-B'), ('6-A', '6-A'), ('6-B', '6-B'), ('7-A', '7-A'), ('7-B', '7-B'), ('8-A', '8-A'), ('8-B', '8-B'), ('9-A', '9-A'), ('9-B', '9-B'), ('10-A', '10-A'), ('10-B', '10-B'), ('11-A', '11-A'), ('11-B', '11-B')], default='Немає', max_length=5, verbose_name='Керівние класу'),
        ),
    ]
