# Generated by Django 3.2.19 on 2023-06-28 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Estimates',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('login', models.CharField(choices=[('1-A', '1-A'), ('1-B', '1-B'), ('2-A', '2-A'), ('2-B', '2-B'), ('3-A', '3-A'), ('3-B', '3-B'), ('4-A', '4-A'), ('4-B', '4-B'), ('5-A', '5-A'), ('5-B', '5-B'), ('6-A', '6-A'), ('6-B', '6-B'), ('7-A', '7-A'), ('7-B', '7-B'), ('8-A', '8-A'), ('8-B', '8-B'), ('9-A', '9-A'), ('9-B', '9-B'), ('10-A', '10-A'), ('10-B', '10-B'), ('11-A', '11-A'), ('11-B', '11-B')], max_length=4, unique=True, verbose_name='Логін')),
                ('predmet', models.CharField(choices=[('Алгебра', 'Алгебра'), ('Англійська мова', 'Англійська мова'), ('Астрономія', 'Астрономія'), ('Біологія', 'Біологія'), ('Біологія і екологія', 'Біологія і екологія'), ('Географія', 'Географія'), ('Геометрія', 'Геометрія'), ('Громадянська освіти', 'Громадянська освіти'), ('Зарубіжна література', 'Зарубіжна література'), ('Інформатика', 'Інформатика'), ('Історія', 'Історія'), ('Історія України', 'Історія України'), ('Математика', 'Математика'), ('Мистецтво', 'Мистецтво'), ('Музика', 'Музика'), ('Основи здоров’я', 'Основи здоров’я'), ('Правознавство', 'Правознавство'), ('Природа', 'Природа'), ('Технології', 'Технології'), ('Українська література', 'Українська література'), ('Українська мова', 'Українська мова'), ('Фізика', 'Фізика'), ('Фізична культура', 'Фізична культура'), ('Хімія', 'Хімія'), ('Я досліджую світ', 'Я досліджую світ')], max_length=255, unique=True, verbose_name='Предмет')),
                ('estimate', models.CharField(default='', max_length=255, verbose_name='Оцінки')),
            ],
            options={
                'verbose_name': 'Завдання класу',
                'verbose_name_plural': 'Завдання класів',
            },
        ),
        migrations.CreateModel(
            name='Rozk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clas', models.CharField(choices=[('1-A', '1-A'), ('1-B', '1-B'), ('2-A', '2-A'), ('2-B', '2-B'), ('3-A', '3-A'), ('3-B', '3-B'), ('4-A', '4-A'), ('4-B', '4-B'), ('5-A', '5-A'), ('5-B', '5-B'), ('6-A', '6-A'), ('6-B', '6-B'), ('7-A', '7-A'), ('7-B', '7-B'), ('8-A', '8-A'), ('8-B', '8-B'), ('9-A', '9-A'), ('9-B', '9-B'), ('10-A', '10-A'), ('10-B', '10-B'), ('11-A', '11-A'), ('11-B', '11-B')], max_length=4, unique=True, verbose_name='Клас')),
                ('Monday', models.TextField(default='', max_length=255, verbose_name='Понеділок')),
                ('Tuesday', models.TextField(default='', max_length=255, verbose_name='Вівторок')),
                ('Wednesday', models.TextField(default='', max_length=255, verbose_name='Середа')),
                ('Thursday', models.TextField(default='', max_length=255, verbose_name='Четверг')),
                ('Friday', models.TextField(default='', max_length=255, verbose_name="П'ятниця")),
            ],
            options={
                'verbose_name': 'Розклад класу',
                'verbose_name_plural': 'Розклади класів',
            },
        ),
        migrations.CreateModel(
            name='Work',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clas', models.CharField(choices=[('1-A', '1-A'), ('1-B', '1-B'), ('2-A', '2-A'), ('2-B', '2-B'), ('3-A', '3-A'), ('3-B', '3-B'), ('4-A', '4-A'), ('4-B', '4-B'), ('5-A', '5-A'), ('5-B', '5-B'), ('6-A', '6-A'), ('6-B', '6-B'), ('7-A', '7-A'), ('7-B', '7-B'), ('8-A', '8-A'), ('8-B', '8-B'), ('9-A', '9-A'), ('9-B', '9-B'), ('10-A', '10-A'), ('10-B', '10-B'), ('11-A', '11-A'), ('11-B', '11-B')], max_length=4, verbose_name='Клас')),
                ('predmet', models.CharField(choices=[('Алгебра', 'Алгебра'), ('Англійська мова', 'Англійська мова'), ('Астрономія', 'Астрономія'), ('Біологія', 'Біологія'), ('Біологія і екологія', 'Біологія і екологія'), ('Географія', 'Географія'), ('Геометрія', 'Геометрія'), ('Громадянська освіти', 'Громадянська освіти'), ('Зарубіжна література', 'Зарубіжна література'), ('Інформатика', 'Інформатика'), ('Історія', 'Історія'), ('Історія України', 'Історія України'), ('Математика', 'Математика'), ('Мистецтво', 'Мистецтво'), ('Музика', 'Музика'), ('Основи здоров’я', 'Основи здоров’я'), ('Правознавство', 'Правознавство'), ('Природа', 'Природа'), ('Технології', 'Технології'), ('Українська література', 'Українська література'), ('Українська мова', 'Українська мова'), ('Фізика', 'Фізика'), ('Фізична культура', 'Фізична культура'), ('Хімія', 'Хімія'), ('Я досліджую світ', 'Я досліджую світ')], max_length=255, verbose_name='Предмет')),
                ('work', models.CharField(default='', max_length=255, verbose_name='Завдання')),
            ],
            options={
                'verbose_name': 'Завдання класу',
                'verbose_name_plural': 'Завдання класів',
            },
        ),
    ]
