# Generated by Django 3.2.19 on 2023-06-28 12:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='estimates',
            options={'verbose_name': 'Оцінки учня', 'verbose_name_plural': 'Оцінки учнів'},
        ),
    ]
