# Generated by Django 3.2.19 on 2023-06-28 12:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20230628_1512'),
        ('student', '0002_alter_estimates_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estimates',
            name='login',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.student'),
        ),
    ]
