# Generated by Django 3.2.19 on 2023-06-29 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0003_alter_estimates_login'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estimates',
            name='estimate',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Оцінки'),
        ),
        migrations.AlterField(
            model_name='work',
            name='work',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Завдання'),
        ),
    ]
